<?php
return array(
    /*
     * Guest controllers.
     */
    array(
        "^$",
        array(""),
        array(""),
        array("blog", "", "", "", "301", array("blog", "", "/",),),
        array("blog", "", "",),
    ),
    array(
        "^/$",
        array("/"),
        array(""),
        array("blog", "", "", "", "301", array("blog", "guest/home.show", "",),),
        array("blog", "", "/",),
    ),
    array(
        "^/home$",
        array("/home"),
        array(""),
        array("blog", "common", "guest/home", "show", "", ""),
        array("blog", "guest/home.show", "",),
    ),
    array(
        "^/about$",
        array("/about"),
        array(""),
        array("blog", "common", "guest/about", "show", "", ""),
        array("blog", "guest/about.show", "",),
    ),

    array(
        "^/articles/index$",
        array("/articles/index"),
        array(""),
        array("blog", "common", "guest/article", "list_all", "", ""),
        array("blog", "guest/article.list_all", "",),
    ),
    array(
        "^/articles/by-tag/(?P<tag_slug>[[:word:]-]+)$",
        array("/articles/by-tag/",),
        array("tag_slug",),
        array("blog", "common", "guest/article", "slug_list_tag", "", ""),
        array("blog", "guest/article.slug_list_tag", "",),
    ),
    //array(
    //    "^/articles\?category_id=(?P<category_id>\d+)$",
    //    array("/articles?category_id=",),
    //    array("category_id",),
    //    array("blog", "common", "guest/article", "list_category", "", ""),
    //    array("blog", "guest/article.list_category", "",),
    //),
    array(
        //"^/articles/(?P<full_category_slug>([[:word:]-]+/)+)index$",
        "^/articles/(?P<full_category_slug>([[:word:]-]+/)*[[:word:]-]+)/index$",
        array("/articles/", "/index"),
        array("full_category_slug", ""),
        array("blog", "common", "guest/article", "slug_list_category", "", ""),
        array("blog", "guest/article.slug_list_category", "",),
    ),
    //array(
    //    "^/article/(?P<id>\d+)$",
    //    array("/article/",),
    //    array("id",),
    //    array("blog", "common", "guest/article", "show", "", ""),
    //    array("blog", "guest/article.show", "",),
    //),
    array(
        "^/articles/(?P<full_slug>([[:word:]-]+/)+[[:word:]-]+)$",
        array("/articles/",),
        array("full_slug",),
        array("blog", "common", "guest/article", "slug_show", "", ""),
        array("blog", "guest/article.slug_show", "",),
    ),


    array(
        "^/categories/index$",
        array("/categories/index"),
        array(""),
        array("blog", "common", "guest/category", "list_all", "", "",),
        array("blog", "guest/category.list_all", "",),
    ),
    //array(
    //    "^/categories/(?P<id>\d+)$",
    //    array("/categories/",),
    //    array("id",),
    //    array("blog", "common", "guest/category", "show", "", "",),
    //    array("blog", "guest/category.show", "",),
    //),
    array(
        //"^/categories/(?P<category_slug>[[:word:]-]+)$",
        "^/categories/(?P<full_slug>([[:word:]-]+/)*[[:word:]-]+)$",
        array("/categories/",),
        array("full_slug",),
        array("blog", "common", "guest/category", "slug_show", "", "",),
        array("blog", "guest/category.slug_show", "",),
    ),

    array(
        "^/tags/index$",
        array("/tags/index"),
        array(""),
        array("blog", "common", "guest/tag", "list_all", "", "",),
        array("blog", "guest/tag.list_all", "",),
    ),
    //array(
    //    "^/tags/(?P<id>\d+)$",
    //    array("/tags/",),
    //    array("id",),
    //    array("blog", "common", "guest/tag", "show", "", "",),
    //    array("blog", "guest/tag.show", "",),
    //),
    array(
        "^/tags/(?P<slug>[[:word:]-]+)$",
        array("/tags/",),
        array("slug",),
        array("blog", "common", "guest/tag", "slug_show", "", "",),
        array("blog", "guest/tag.slug_show", "",),
    ),

    array(
        "^/comments\?action=write&article_id=(?P<article_id>\d+)&target_id=(?P<target_id>\w+)$",
        array("/comments?action=write&article_id=", "&target_id="),
        array("article_id", "target_id"),
        array("blog", "common", "guest/comment", "write", "", "",),
        array("blog", "guest/comment.write", "",),
    ),
    array(
        "^/comments\?action=add$",
        array("/comments?action=add"),
        array(""),
        array("blog", "common", "guest/comment", "add", "", "",),
        array("blog", "guest/comment.add", "",),
    ),


    /*
     * Administrator controllers.
     */
    array(
        "^/admin",
        array("/admin"),
        array(""),
        array(
            array(
                "^$",
                array(""),
                array(""),
                array("blog", "", "", "", "301", array("blog", "admin/home.show", "",),),
                array("blog", "", "",),
            ),
            array(
                "^/$",
                array("/"),
                array(""),
                array("blog", "", "", "", "301", array("blog", "admin/home.show", "",),),
                array("blog", "", "/",),
            ),
            array(
                "^/home\?action=show$",
                array("/home?action=show"),
                array(""),
                array("blog", "common", "admin/home", "show", "", ""),
                array("blog", "admin/home.show", "",),
            ),

            array(
                "^/authentication\?action=write$",
                array("/authentication?action=write"),
                array(""),
                array("blog", "common", "admin/authentication", "write", "", ""),
                array("blog", "admin/authentication.write", "",),
            ),
            array(
                "^/authentication\?action=login$",
                array("/authentication?action=login"),
                array(""),
                array("blog", "common", "admin/authentication", "login", "", ""),
                array("blog", "admin/authentication.login", "",),
            ),
            array(
                "^/authentication\?action=logout$",
                array("/authentication?action=logout"),
                array(""),
                array("blog", "common", "admin/authentication", "logout", "", ""),
                array("blog", "admin/authentication.logout", "",),
            ),

            array(
                "^/settings\?action=show$",
                array("/settings?action=show"),
                array(""),
                array("blog", "common", "admin/settings", "show", "", ""),
                array("blog", "admin/settings.show", "",),
            ),

            array(
                "^/config\?action=write$",
                array("/config?action=write"),
                array(""),
                array("blog", "common", "admin/config", "write", "", ""),
                array("blog", "admin/config.write", "",),
            ),
            array(
                "^/config\?action=save$",
                array("/config?action=save"),
                array(""),
                array("blog", "common", "admin/config", "save", "", ""),
                array("blog", "admin/config.save", "",),
            ),

            array(
                "^/option\?action=edit$",
                array("/option?action=edit"),
                array(""),
                array("blog", "common", "admin/option", "edit", "", ""),
                array("blog", "admin/option.edit", "",),
            ),
            array(
                "^/option\?action=update$",
                array("/option?action=update"),
                array(""),
                array("blog", "common", "admin/option", "update", "", ""),
                array("blog", "admin/option.update", "",),
            ),

            array(
                "^/account\?action=edit$",
                array("/account?action=edit"),
                array(""),
                array("blog", "common", "admin/account", "edit", "", ""),
                array("blog", "admin/account.edit", "",),
            ),
            array(
                "^/account\?action=update$",
                array("/account?action=update"),
                array(""),
                array("blog", "common", "admin/account", "update", "", ""),
                array("blog", "admin/account.update", "",),
            ),

            array(
                "^/articles\?action=list_all$",
                array("/articles?action=list_all"),
                array(""),
                array("blog", "common", "admin/article", "list_all", "", ""),
                array("blog", "admin/article.list_all", "",),
            ),
            array(
                "^/articles\?action=list_category&category_id=(?P<category_id>\d+)$",
                array("/articles?action=list_category&category_id=",),
                array("category_id",),
                array("blog", "common", "admin/article", "list_category", "", ""),
                array("blog", "admin/article.list_category", "",),
            ),
            array(
                "^/articles\?action=list_tag&tag_id=(?P<tag_id>\d+)$",
                array("/articles?action=list_tag&tag_id=",),
                array("tag_id",),
                array("blog", "common", "admin/article", "list_tag", "", ""),
                array("blog", "admin/article.list_tag", "",),
            ),
            array(
                "^/articles\?action=show&id=(?P<id>\d+)$",
                array("/articles?action=show&id=",),
                array("id",),
                array("blog", "common", "admin/article", "show", "", ""),
                array("blog", "admin/article.show", "",),
            ),
            array(
                "^/articles\?action=write$",
                array("/articles?action=write"),
                array(""),
                array("blog", "common", "admin/article", "write", "", ""),
                array("blog", "admin/article.write", "",),
            ),
            array(
                "^/articles\?action=add$",
                array("/articles?action=add"),
                array(""),
                array("blog", "common", "admin/article", "add", "", ""),
                array("blog", "admin/article.add", "",),
            ),
            array(
                "^/articles\?action=edit&id=(?P<id>\d+)$",
                array("/articles?action=edit&id="),
                array("id"),
                array("blog", "common", "admin/article", "edit", "", ""),
                array("blog", "admin/article.edit", "",),
            ),
            array(
                "^/articles\?action=update$",
                array("/articles?action=update"),
                array(""),
                array("blog", "common", "admin/article", "update", "", ""),
                array("blog", "admin/article.update", "",),
            ),
            array(
                "^/articles\?action=delete_confirm&id=(?P<id>\d+)$",
                array("/articles?action=delete_confirm&id="),
                array("id"),
                array("blog", "common", "admin/article", "delete_confirm", "", ""),
                array("blog", "admin/article.delete_confirm", "",),
            ),
            array(
                "^/articles\?action=delete$",
                array("/articles?action=delete"),
                array(""),
                array("blog", "common", "admin/article", "delete", "", ""),
                array("blog", "admin/article.delete", "",),
            ),

            array(
                "^/categories\?action=list_all$",
                array("/categories?action=list_all"),
                array(""),
                array("blog", "common", "admin/category", "list_all", "", "",),
                array("blog", "admin/category.list_all", "",),
            ),
            array(
                "^/categories\?action=show&id=(?P<id>\d+)$",
                array("/categories?action=show&id=",),
                array("id",),
                array("blog", "common", "admin/category", "show", "", "",),
                array("blog", "admin/category.show", "",),
            ),
            array(
                "^/categories\?action=write$",
                array("/categories?action=write"),
                array(""),
                array("blog", "common", "admin/category", "write", "", "",),
                array("blog", "admin/category.write", "",),
            ),
            array(
                "^/categories\?action=add$",
                array("/categories?action=add"),
                array(""),
                array("blog", "common", "admin/category", "add", "", "",),
                array("blog", "admin/category.add", "",),
            ),
            array(
                "^/categories\?action=edit\?id=(?P<id>\d+)$",
                array("/categories?action=edit?id="),
                array("id"),
                array("blog", "common", "admin/category", "edit", "", "",),
                array("blog", "admin/category.edit", "",),
            ),
            array(
                "^/categories\?action=update$",
                array("/categories?action=update"),
                array(""),
                array("blog", "common", "admin/category", "update", "", "",),
                array("blog", "admin/category.update", "",),
            ),
            array(
                "^/categories\?action=delete_confirm&id=(?P<id>\d+)$",
                array("/categories?action=delete_confirm&id="),
                array("id"),
                array("blog", "common", "admin/category", "delete_confirm", "", "",),
                array("blog", "admin/category.delete_confirm", "",),
            ),
            array(
                "^/categories\?action=delete$",
                array("/categories?action=delete"),
                array(""),
                array("blog", "common", "admin/category", "delete", "", "",),
                array("blog", "admin/category.delete", "",),
            ),

            array(
                "^/tags\?action=list_all$",
                array("/tags?action=list_all"),
                array(""),
                array("blog", "common", "admin/tag", "list_all", "", "",),
                array("blog", "admin/tag.list_all", "",),
            ),
            array(
                "^/tags\?action=show&id=(?P<id>\d+)$",
                array("/tags?action=show&id=",),
                array("id",),
                array("blog", "common", "admin/tag", "show", "", "",),
                array("blog", "admin/tag.show", "",),
            ),
            array(
                "^/tags\?action=write$",
                array("/tags?action=write"),
                array(""),
                array("blog", "common", "admin/tag", "write", "", "",),
                array("blog", "admin/tag.write", "",),
            ),
            array(
                "^/tags\?action=add$",
                array("/tags?action=add"),
                array(""),
                array("blog", "common", "admin/tag", "add", "", "",),
                array("blog", "admin/tag.add", "",),
            ),
            array(
                "^/tags\?action=edit\?id=(?P<id>\d+)$",
                array("/tags?action=edit?id="),
                array("id"),
                array("blog", "common", "admin/tag", "edit", "", "",),
                array("blog", "admin/tag.edit", "",),
            ),
            array(
                "^/tags\?action=update$",
                array("/tags?action=update"),
                array(""),
                array("blog", "common", "admin/tag", "update", "", "",),
                array("blog", "admin/tag.update", "",),
            ),
            array(
                "^/tags\?action=delete_confirm&id=(?P<id>\d+)$",
                array("/tags?action=delete_confirm&id="),
                array("id"),
                array("blog", "common", "admin/tag", "delete_confirm", "", "",),
                array("blog", "admin/tag.delete_confirm", "",),
            ),
            array(
                "^/tags\?action=delete$",
                array("/tags?action=delete"),
                array(""),
                array("blog", "common", "admin/tag", "delete", "", "",),
                array("blog", "admin/tag.delete", "",),
            ),

            array(
                "^/medias\?action=list_all$",
                array("/medias?action=list_all"),
                array(""),
                array("blog", "common", "admin/media", "list_all", "", "",),
                array("blog", "admin/media.list_all", "",),
            ),
            array(
                "^/medias\?action=list_article&article_id=(?P<article_id>\d+)$",
                array("/medias?action=list_article&article_id="),
                array("article_id"),
                array("blog", "common", "admin/media", "list_article", "", "",),
                array("blog", "admin/media.list_article", "",),
            ),
            array(
                "^/medias\?action=show&id=(?P<id>\d+)$",
                array("/medias?action=show&id=",),
                array("id",),
                array("blog", "common", "admin/media", "show", "", "",),
                array("blog", "admin/media.show", "",),
            ),
            array(
                "^/medias\?action=write$",
                array("/medias?action=write"),
                array(""),
                array("blog", "common", "admin/media", "write", "", "",),
                array("blog", "admin/media.write", "",),
            ),
            array(
                "^/medias\?action=add$",
                array("/medias?action=add"),
                array(""),
                array("blog", "common", "admin/media", "add", "", "",),
                array("blog", "admin/media.add", "",),
            ),
            array(
                "^/medias\?action=edit\?id=(?P<id>\d+)$",
                array("/medias?action=edit?id="),
                array("id"),
                array("blog", "common", "admin/media", "edit", "", "",),
                array("blog", "admin/media.edit", "",),
            ),
            array(
                "^/medias\?action=update$",
                array("/medias?action=update"),
                array(""),
                array("blog", "common", "admin/media", "update", "", "",),
                array("blog", "admin/media.update", "",),
            ),
            array(
                "^/medias\?action=delete_confirm&id=(?P<id>\d+)$",
                array("/medias?action=delete_confirm&id="),
                array("id"),
                array("blog", "common", "admin/media", "delete_confirm", "", "",),
                array("blog", "admin/media.delete_confirm", "",),
            ),
            array(
                "^/medias\?action=delete$",
                array("/medias?action=delete"),
                array(""),
                array("blog", "common", "admin/media", "delete", "", "",),
                array("blog", "admin/media.delete", "",),
            ),

            array(
                "^/comments\?action=list_all$",
                array("/comments?action=list_all"),
                array(""),
                array("blog", "common", "admin/comment", "list_all", "", "",),
                array("blog", "admin/comment.list_all", "",),
            ),
            array(
                "^/comments\?action=write&article_id=(?P<article_id>\d+)&target_id=(?P<target_id>\w+)$",
                array("/comments?action=write&article_id=", "&target_id="),
                array("article_id", "target_id"),
                array("blog", "common", "admin/comment", "write", "", "",),
                array("blog", "admin/comment.write", "",),
            ),
            array(
                "^/comments\?action=add$",
                array("/comments?action=add"),
                array(""),
                array("blog", "common", "admin/comment", "add", "", "",),
                array("blog", "admin/comment.add", "",),
            ),
            array(
                "^/comments\?action=delete_confirm&id=(?P<id>\d+)$",
                array("/comments?action=delete_confirm&id="),
                array("id"),
                array("blog", "common", "admin/comment", "delete_confirm", "", "",),
                array("blog", "admin/comment.delete_confirm", "",),
            ),
            array(
                "^/comments\?action=delete$",
                array("/comments?action=delete"),
                array(""),
                array("blog", "common", "admin/comment", "delete", "", "",),
                array("blog", "admin/comment.delete", "",),
            ),

            /*
             * Text mode
             */
            array(
                "^/articles\?mode=text&action=list_category&category_id=(?P<category_id>\d+)$",
                array("/articles?mode=text&action=list_category&category_id=",),
                array("category_id",),
                array("blog", "common", "admin/article", "list_category", "text", ""),
                array("blog", "admin/article.list_category", "text",),
            ),

            array(
                "^/comments\?mode=text&action=list_all$",
                array("/comments?mode=text&action=list_all"),
                array(""),
                array("blog", "common", "admin/comment", "list_all", "text", "",),
                array("blog", "admin/comment.list_all", "text",),
            ),
        ),
    ),
);
?>
